### ISSUE TITLE
[Feature Request] Option to Disable/Ignore UIImageOrientation

### ISSUE THREAD

**Issue by victorguo** [genkikondo/GKImagePicker#2]
Hi, thank you for the great work.

I found that when I take a photo in the position home button down, just the default UIImageOrientation, it will rotate -90 degrees which is not my intent.

The same situation occurs when I select a photo from the gallery which is took in the position home button down.

Could you please add a feature for us to disable/ignore UIImageOrientation, or tell me how can I deal with it?

Thank you.

**Comment by enryold** [comment]
I've fixed this problem right now by including this category. 

http://stackoverflow.com/questions/5427656/ios-uiimagepickercontroller-result-image-orientation-after-upload

And call it in GKImageCropper.m changing the function imageFromView (line 216) in this way:

``` objc
UIImage* imageFromView(UIImage* srcImage, CGRect* rect) {

    UIImage *fixOrientation = [srcImage fixOrientation];
    CGImageRef cr = CGImageCreateWithImageInRect(fixOrientation.CGImage, *rect);
    UIImage* cropped = [UIImage imageWithCGImage:cr];
    CGImageRelease(cr);
    return cropped;
}
```

**Comment by genkikondo** [comment]
Perfect, thanks for that fix. It seems to be working.

**Comment by victorguo** [comment]
Thank you guys so much!
